import { useState } from 'react';

const DATA_BROKERS = [
  { id: 'truecaller', name: 'Truecaller' },
  { id: 'spokeo', name: 'Spokeo' },
  { id: 'intelius', name: 'Intelius' },
  { id: 'beenverified', name: 'BeenVerified' },
  { id: 'pipl', name: 'Pipl' },
  { id: 'whitepages', name: 'Whitepages India' },
  { id: 'justdial', name: 'Just Dial' },
  { id: 'linkedin', name: 'LinkedIn (data export)' },
  { id: 'custom', name: 'Custom / Other' },
];

function generateLetter({ fullName, email, phone, address, broker, customBroker, dataTypes, additionalDetails }) {
  const target = broker === 'custom' ? customBroker : DATA_BROKERS.find(b => b.id === broker)?.name || broker;
  const today = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  const dataList = dataTypes.length > 0 ? dataTypes.join(', ') : 'all personal data including name, email, phone number, and address';

  return `${today}

To: The Data Protection Officer / Legal Team
${target}

Subject: Formal Request for Erasure of Personal Data under Section 13 of the Digital Personal Data Protection Act, 2023 (DPDP Act) and Right to Erasure

Dear Data Protection Officer,

I, ${fullName || '[YOUR FULL NAME]'}, am writing to formally request the erasure of all personal data that you hold, process, or have shared with any third party relating to me, as guaranteed under the Digital Personal Data Protection Act, 2023 (hereinafter "DPDP Act"), and where applicable, under provisions analogous to Article 17 of the General Data Protection Regulation (GDPR).

1. IDENTIFICATION OF DATA SUBJECT

   Full Name: ${fullName || '[YOUR FULL NAME]'}
   Email Address: ${email || '[YOUR EMAIL]'}
   Phone Number: ${phone || '[YOUR PHONE NUMBER]'}
   Address: ${address || '[YOUR ADDRESS]'}

2. NATURE OF DATA HELD

   I request the immediate and permanent erasure of the following categories of personal data relating to me that are in your possession, custody or control:
   ${dataList.split(', ').map(d => `   - ${d}`).join('\n')}
   ${additionalDetails ? `\n   Additional context: ${additionalDetails}` : ''}

3. LEGAL BASIS FOR THIS REQUEST

   Under Section 12 and Section 13 of the DPDP Act, 2023, I, as a Data Principal, have the right to:
   (a) Know the personal data you hold about me and the purposes for which it is processed;
   (b) Correction and erasure of personal data where it is no longer necessary for the specified purpose;
   (c) Grievance redressal within a reasonable period.

   Pursuant to Section 13(1)(b), I withdraw any consent previously given for the processing of my personal data. My personal data was collected without my explicit consent and is being processed without a lawful basis under Section 4 of the Act.

4. YOUR OBLIGATIONS UNDER THE DPDP ACT, 2023

   As a Data Fiduciary operating in India, you are bound by Section 8 of the Act to:
   - Process personal data only for specified lawful purposes;
   - Erase personal data upon withdrawal of consent or upon the Data Principal's request where processing is no longer necessary;
   - Respond to this grievance within 48 hours of receipt per Section 13(3).

5. REQUESTED ACTIONS

   I formally request that you:
   (a) Immediately cease all processing of my personal data;
   (b) Permanently erase all copies of my personal data from your systems and databases, including any backups;
   (c) Notify all third parties to whom my data has been disclosed and instruct them to erase it;
   (d) Confirm in writing within 48 hours that the above actions have been taken.

6. NON-COMPLIANCE CONSEQUENCES

   Failure to comply with this request within the stipulated timeframe constitutes a violation of the DPDP Act, 2023. I reserve the right to:
   - File a complaint with the Data Protection Board of India under Section 28 of the DPDP Act;
   - Seek compensation under applicable legal provisions;
   - Escalate to relevant regulatory and consumer forums.

I expect a written confirmation of this erasure within 48 hours of receipt of this notice. Please provide confirmation to: ${email || '[YOUR EMAIL]'}

Issued Without Prejudice,

${fullName || '[YOUR FULL NAME]'}
${phone || ''}
${email || ''}
${address || ''}

---
This letter was generated in compliance with the Digital Personal Data Protection Act, 2023 (India). Generated by PrivacyRadar — Team CipherX | CIPHATHO 26'. This document is for legal purposes only.`;
}

export default function LegalLetterPage() {
  const [step, setStep] = useState(1);
  const [form, setForm] = useState({
    fullName: '', email: '', phone: '', address: '',
    broker: '', customBroker: '',
    dataTypes: [],
    additionalDetails: '',
  });
  const [copied, setCopied] = useState(false);

  const update = (field, val) => setForm(f => ({ ...f, [field]: val }));
  const toggleDataType = (dt) => {
    setForm(f => ({
      ...f,
      dataTypes: f.dataTypes.includes(dt)
        ? f.dataTypes.filter(d => d !== dt)
        : [...f.dataTypes, dt],
    }));
  };

  const letter = generateLetter(form);

  const copyLetter = () => {
    navigator.clipboard.writeText(letter).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const downloadLetter = () => {
    const blob = new Blob([letter], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `DPDP_Erasure_Request_${form.fullName.replace(/\s+/g, '_') || 'Letter'}.txt`;
    a.click();
  };

  const DATA_TYPES = ['Name', 'Email', 'Phone Number', 'Address', 'Date of Birth', 'Aadhaar', 'PAN', 'Financial Info', 'Location Data', 'Photos', 'Browsing History', 'All Personal Data'];

  return (
    <div style={{ minHeight: '100vh', padding: '80px 24px', position: 'relative', zIndex: 1 }}>
      <div className="container" style={{ maxWidth: '860px' }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <div style={{
            display: 'inline-block', padding: '6px 16px', marginBottom: '16px',
            background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.3)',
            borderRadius: '20px', fontSize: '12px', fontFamily: 'Space Mono', color: 'var(--accent-success)',
          }}>
            ⚖️ DPDP ACT 2023 COMPLIANT
          </div>
          <h1 style={{ fontSize: 'clamp(24px,4vw,42px)', marginBottom: '12px' }}>
            Legal <span className="gradient-text">Data Erasure</span> Letter
          </h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: '16px', maxWidth: '520px', margin: '0 auto' }}>
            Generate a legally compliant data removal request under Section 13 of India's DPDP Act, 2023.
          </p>
        </div>

        {/* Step progress */}
        <div style={{ display: 'flex', gap: '0', marginBottom: '32px', borderRadius: '10px', overflow: 'hidden', border: '1px solid var(--border)' }}>
          {['Your Details', 'Choose Target', 'Preview & Export'].map((label, i) => (
            <div key={i} onClick={() => step > i + 1 && setStep(i + 1)}
              style={{
                flex: 1, padding: '12px', textAlign: 'center', fontSize: '13px',
                fontFamily: 'Space Mono', cursor: step > i + 1 ? 'pointer' : 'default',
                background: step === i + 1 ? 'rgba(0,212,255,0.1)' : 'transparent',
                color: step === i + 1 ? 'var(--accent-primary)' : step > i + 1 ? 'var(--accent-success)' : 'var(--text-secondary)',
                borderRight: i < 2 ? '1px solid var(--border)' : 'none',
              }}>
              {step > i + 1 ? '✓ ' : `${i + 1}. `}{label}
            </div>
          ))}
        </div>

        {/* Step 1: Your Details */}
        {step === 1 && (
          <div className="card" style={{ padding: '28px' }}>
            <h2 style={{ fontSize: '16px', marginBottom: '20px' }}>Your Personal Details</h2>
            <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '20px', fontFamily: 'Space Mono' }}>
              ℹ️ This information is used only to generate the letter and is never stored or sent anywhere.
            </p>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              {[
                { label: 'Full Name *', field: 'fullName', placeholder: 'Rahul Sharma' },
                { label: 'Email Address *', field: 'email', placeholder: 'rahul@example.com' },
                { label: 'Phone Number', field: 'phone', placeholder: '+91 98765 43210' },
                { label: 'Address / City', field: 'address', placeholder: 'Mumbai, Maharashtra' },
              ].map(({ label, field, placeholder }) => (
                <div key={field}>
                  <label style={{ display: 'block', fontSize: '11px', fontFamily: 'Space Mono', color: 'var(--text-secondary)', marginBottom: '6px' }}>{label}</label>
                  <input
                    className="input-field"
                    value={form[field]}
                    onChange={e => update(field, e.target.value)}
                    placeholder={placeholder}
                    style={{ width: '100%', boxSizing: 'border-box' }}
                  />
                </div>
              ))}
            </div>
            <div style={{ marginTop: '24px' }}>
              <label style={{ display: 'block', fontSize: '11px', fontFamily: 'Space Mono', color: 'var(--text-secondary)', marginBottom: '10px' }}>
                DATA TYPES TO REQUEST ERASURE OF
              </label>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                {DATA_TYPES.map(dt => (
                  <button key={dt} onClick={() => toggleDataType(dt)}
                    style={{
                      padding: '6px 14px', fontSize: '12px', borderRadius: '20px', cursor: 'pointer',
                      border: `1px solid ${form.dataTypes.includes(dt) ? 'var(--accent-primary)' : 'var(--border)'}`,
                      background: form.dataTypes.includes(dt) ? 'rgba(0,212,255,0.1)' : 'transparent',
                      color: form.dataTypes.includes(dt) ? 'var(--accent-primary)' : 'var(--text-secondary)',
                      transition: 'all 0.2s',
                    }}>
                    {form.dataTypes.includes(dt) ? '✓ ' : ''}{dt}
                  </button>
                ))}
              </div>
            </div>
            <button className="btn-primary" style={{ marginTop: '24px', width: '100%' }}
              onClick={() => setStep(2)} disabled={!form.fullName || !form.email}>
              Next: Choose Target →
            </button>
          </div>
        )}

        {/* Step 2: Choose broker */}
        {step === 2 && (
          <div className="card" style={{ padding: '28px' }}>
            <h2 style={{ fontSize: '16px', marginBottom: '20px' }}>Select Data Broker / Platform</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: '10px', marginBottom: '20px' }}>
              {DATA_BROKERS.map(b => (
                <button key={b.id} onClick={() => update('broker', b.id)}
                  style={{
                    padding: '14px', fontSize: '13px', borderRadius: '8px', cursor: 'pointer', textAlign: 'left',
                    border: `1px solid ${form.broker === b.id ? 'var(--accent-primary)' : 'var(--border)'}`,
                    background: form.broker === b.id ? 'rgba(0,212,255,0.08)' : 'rgba(15,25,35,0.4)',
                    color: form.broker === b.id ? 'var(--accent-primary)' : 'var(--text-primary)',
                    transition: 'all 0.2s',
                    fontFamily: form.broker === b.id ? 'Space Mono' : 'inherit',
                  }}>
                  {form.broker === b.id ? '✓ ' : ''}{b.name}
                </button>
              ))}
            </div>
            {form.broker === 'custom' && (
              <div style={{ marginBottom: '16px' }}>
                <label style={{ display: 'block', fontSize: '11px', fontFamily: 'Space Mono', color: 'var(--text-secondary)', marginBottom: '6px' }}>CUSTOM ORGANIZATION NAME</label>
                <input
                  className="input-field"
                  value={form.customBroker}
                  onChange={e => update('customBroker', e.target.value)}
                  placeholder="e.g., My Old Employer, SomeApp Ltd."
                  style={{ width: '100%', boxSizing: 'border-box' }}
                />
              </div>
            )}
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', fontSize: '11px', fontFamily: 'Space Mono', color: 'var(--text-secondary)', marginBottom: '6px' }}>ADDITIONAL DETAILS (OPTIONAL)</label>
              <textarea
                className="input-field"
                value={form.additionalDetails}
                onChange={e => update('additionalDetails', e.target.value)}
                placeholder="Any additional context, account IDs, URLs of your profile, etc."
                rows={3}
                style={{ width: '100%', boxSizing: 'border-box', resize: 'vertical', fontFamily: 'JetBrains Mono', fontSize: '13px' }}
              />
            </div>
            <div style={{ display: 'flex', gap: '12px' }}>
              <button className="btn-outline" onClick={() => setStep(1)}>← Back</button>
              <button className="btn-primary" style={{ flex: 1 }}
                onClick={() => setStep(3)}
                disabled={!form.broker || (form.broker === 'custom' && !form.customBroker)}>
                Preview Letter →
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Preview & Export */}
        {step === 3 && (
          <div>
            <div className="card" style={{ padding: '24px', marginBottom: '20px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
              <div>
                <div style={{ fontSize: '15px', fontFamily: 'Space Mono', marginBottom: '4px' }}>✅ Your legal letter is ready</div>
                <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>Copy it, download as .txt, or print to PDF</div>
              </div>
              <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                <button className="btn-primary" onClick={copyLetter}>
                  {copied ? '✓ Copied!' : '📋 Copy Letter'}
                </button>
                <button className="btn-outline" onClick={downloadLetter}>⬇ Download .txt</button>
                <button className="btn-outline" onClick={() => window.print()}>🖨️ Print / PDF</button>
              </div>
            </div>

            {/* Warning about legal advice */}
            <div style={{ background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.3)', borderRadius: '8px', padding: '12px 16px', marginBottom: '16px', fontSize: '12px', color: 'var(--text-secondary)' }}>
              ⚠️ This is a template. Consider having a legal professional review it before sending. Not a substitute for legal advice.
            </div>

            {/* Letter preview */}
            <div className="card" style={{ padding: '0', overflow: 'hidden' }}>
              <div style={{ background: 'rgba(0,212,255,0.05)', borderBottom: '1px solid var(--border)', padding: '10px 20px', display: 'flex', gap: '6px', alignItems: 'center' }}>
                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#FF3B3B' }} />
                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#F59E0B' }} />
                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#10B981' }} />
                <span style={{ marginLeft: '8px', fontSize: '12px', color: 'var(--text-secondary)', fontFamily: 'Space Mono' }}>
                  DPDP_Erasure_Request.txt
                </span>
              </div>
              <pre style={{
                padding: '24px',
                fontSize: '12px',
                fontFamily: 'JetBrains Mono',
                lineHeight: 1.8,
                color: 'var(--text-secondary)',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
                maxHeight: '520px',
                overflowY: 'auto',
                margin: 0,
              }}>
                {letter}
              </pre>
            </div>

            <div style={{ textAlign: 'center', marginTop: '20px' }}>
              <button className="btn-outline" onClick={() => setStep(1)}>← Edit Details</button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
